<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <Authors>白宇丹</Authors>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GIS.Display\GIS.Display.csproj" />
    <ProjectReference Include="..\..\模块5_PostGIS交互_李雨晴\GIS.PostGIS\GIS.PostGIS.csproj" />
  </ItemGroup>
</Project>

