<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <Authors>白宇丹</Authors>
    <Description>模块2：地图显示、图层管理和鼠标选择</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\MapObjects\GIS\GIS.csproj" />
  </ItemGroup>
</Project>

